### ISSUE TITLE
mu clone workflow requires multiple .mu_repo files

### ISSUE THREAD

**Issue by rasmusskovdk** [fabioz/mu-repo#56] opened 2019-06-25 11:59 UTC
I like the `mu clone` workflow, so I checked this .mu_repo file into my "main" repo:

> repo=.
> repo=..\depA
> serial=True

After I cloned the the "main" repo and its dependencies into a root folder, I still want to be able to use mu (e.g. `mu rb`). When I'm outside the main repo (e.g. in root or depA) mu can't see any .mu_repo file and will no longer work.

Should I maintain a separate .mu_repo file in my root folder?

**Comment by fabioz** [comment] 2019-06-25 12:25
Well, there are 2 choices there... you can either enter that repository and do mu commands from there (so, you'd `cd` into the cloned repo and do `mu rb` from there when you want) or you can have a separate `.mu_repo` file on the root folder (both are valid choices and you can choose what works best for you).

p.s.: I'm closing the issue because it's working as intended.

**Closed by fabioz** 2019-06-25 12:25 UTC
